server:
  port: 8782

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8787/eureka/
      #defaultZone: http://192.168.6.131:8780/eureka/

spring:
  application:
    name: usercontroller
  thymeleaf:
    prefix: classpath:/templates/